/*
Deployment script for TargetDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "TargetDB"
:setvar DefaultFilePrefix "TargetDB"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Starting rebuilding table [dbo].[DeletedRowSet]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_DeletedRowSet] (
    [Name]        NVARCHAR (10) NOT NULL,
    [Surname]     NVARCHAR (10) NOT NULL,
    [Phone]       NVARCHAR (50) NOT NULL,
    [Id]          INT           NOT NULL,
    [Description] NVARCHAR (50) NOT NULL,
    [InsertDate]  DATE          NOT NULL,
    [Checksum]    INT           NOT NULL,
    [Status]      VARCHAR (1)   CONSTRAINT [DF_DeletedRowSet_Status] DEFAULT ('N') NOT NULL,
    [JobId]       INT           NULL,
    [LogId]       INT           NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_DeletedRowSet1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[DeletedRowSet])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_DeletedRowSet] ([Id], [Name], [Surname], [Phone], [Description], [InsertDate], [Checksum], [Status], [JobId], [LogId])
        SELECT   [Id],
                 [Name],
                 [Surname],
                 [Phone],
                 [Description],
                 [InsertDate],
                 [Checksum],
                 [Status],
                 [JobId],
                 [LogId]
        FROM     [dbo].[DeletedRowSet]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[DeletedRowSet];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_DeletedRowSet]', N'DeletedRowSet';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_DeletedRowSet1]', N'PK_DeletedRowSet', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[InsertedRowSet]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_InsertedRowSet] (
    [Name]        NVARCHAR (10) NOT NULL,
    [Surname]     NVARCHAR (10) NOT NULL,
    [Phone]       NVARCHAR (50) NOT NULL,
    [Id]          INT           NOT NULL,
    [Description] NVARCHAR (50) NOT NULL,
    [InsertDate]  DATE          NOT NULL,
    [Checksum]    INT           NOT NULL,
    [Status]      VARCHAR (1)   CONSTRAINT [DF_InsertedRowSet_Status] DEFAULT ('N') NOT NULL,
    [JobId]       INT           NULL,
    [LogId]       INT           NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_InsertedRowSet1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[InsertedRowSet])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_InsertedRowSet] ([Id], [Name], [Surname], [Phone], [Description], [InsertDate], [Checksum], [Status], [JobId], [LogId])
        SELECT   [Id],
                 [Name],
                 [Surname],
                 [Phone],
                 [Description],
                 [InsertDate],
                 [Checksum],
                 [Status],
                 [JobId],
                 [LogId]
        FROM     [dbo].[InsertedRowSet]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[InsertedRowSet];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_InsertedRowSet]', N'InsertedRowSet';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_InsertedRowSet1]', N'PK_InsertedRowSet', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[SimplePatient]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_SimplePatient] (
    [Name]        NVARCHAR (10) NOT NULL,
    [Surname]     NVARCHAR (10) NOT NULL,
    [Phone]       NVARCHAR (50) NOT NULL,
    [Id]          INT           NOT NULL,
    [Description] NVARCHAR (50) NOT NULL,
    [InsertDate]  DATE          NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_SimplePatient1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[SimplePatient])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_SimplePatient] ([Id], [Name], [Surname], [Phone], [Description], [InsertDate])
        SELECT   [Id],
                 [Name],
                 [Surname],
                 [Phone],
                 [Description],
                 [InsertDate]
        FROM     [dbo].[SimplePatient]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[SimplePatient];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_SimplePatient]', N'SimplePatient';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_SimplePatient1]', N'PK_SimplePatient', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[UpdatedRowSet]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_UpdatedRowSet] (
    [Name]        NVARCHAR (10) NOT NULL,
    [Surname]     NVARCHAR (10) NOT NULL,
    [Phone]       NVARCHAR (50) NOT NULL,
    [Id]          INT           NOT NULL,
    [Description] NVARCHAR (50) NOT NULL,
    [InsertDate]  DATE          NOT NULL,
    [Checksum]    INT           NOT NULL,
    [Status]      VARCHAR (1)   CONSTRAINT [DF_UpdatedRowSet_Status] DEFAULT ('N') NOT NULL,
    [JobId]       INT           NULL,
    [LogId]       INT           NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_UpdatedRowSet1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[UpdatedRowSet])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_UpdatedRowSet] ([Id], [Name], [Surname], [Phone], [Description], [InsertDate], [Checksum], [Status], [JobId], [LogId])
        SELECT   [Id],
                 [Name],
                 [Surname],
                 [Phone],
                 [Description],
                 [InsertDate],
                 [Checksum],
                 [Status],
                 [JobId],
                 [LogId]
        FROM     [dbo].[UpdatedRowSet]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[UpdatedRowSet];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_UpdatedRowSet]', N'UpdatedRowSet';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_UpdatedRowSet1]', N'PK_UpdatedRowSet', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[StoreChecksumSimplePatient]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_StoreChecksumSimplePatient] (
    [Name]        NVARCHAR (10) NOT NULL,
    [Surname]     NVARCHAR (10) NOT NULL,
    [Phone]       NVARCHAR (50) NOT NULL,
    [Id]          INT           NOT NULL,
    [Description] NVARCHAR (50) NOT NULL,
    [InsertDate]  DATE          NOT NULL,
    [Checksum]    INT           NOT NULL,
    [Status]      VARCHAR (1)   CONSTRAINT [DF_StoreChecksumSimplePatient_Status] DEFAULT ('N') NOT NULL,
    [JobId]       INT           NULL,
    [LogId]       INT           NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_StoreChecksumSimplePatient1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[StoreChecksumSimplePatient])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_StoreChecksumSimplePatient] ([Id], [Name], [Surname], [Phone], [Description], [InsertDate], [Checksum], [Status], [JobId], [LogId])
        SELECT   [Id],
                 [Name],
                 [Surname],
                 [Phone],
                 [Description],
                 [InsertDate],
                 [Checksum],
                 [Status],
                 [JobId],
                 [LogId]
        FROM     [dbo].[StoreChecksumSimplePatient]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[StoreChecksumSimplePatient];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_StoreChecksumSimplePatient]', N'StoreChecksumSimplePatient';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK_StoreChecksumSimplePatient1]', N'PK_StoreChecksumSimplePatient', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Update complete.';


GO
