USE [master]
GO

CREATE DATABASE [SamplePatient]
GO

USE [SamplePatient]
GO
/****** Object:  Table [dbo].[DeletedRowSet]    Script Date: 4/21/2020 6:42:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DeletedRowSet](
	[Name] [nvarchar](10) NOT NULL,
	[Surname] [nvarchar](10) NOT NULL,
	[Phone] [nvarchar](50) NOT NULL,
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[InsertDate] [date] NOT NULL,
	[Checksum] [int] NOT NULL,
	[Status] [varchar](1) NOT NULL,
	[JobId] [int] NULL,
	[LogId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[InsertedRowSet]    Script Date: 4/21/2020 6:42:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[InsertedRowSet](
	[Name] [nvarchar](10) NOT NULL,
	[Surname] [nvarchar](10) NOT NULL,
	[Phone] [nvarchar](50) NOT NULL,
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[InsertDate] [date] NOT NULL,
	[Checksum] [int] NOT NULL,
	[Status] [varchar](1) NOT NULL,
	[JobId] [int] NULL,
	[LogId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Job]    Script Date: 4/21/2020 6:42:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Job](
	[JobId] [int] IDENTITY(1,1) NOT NULL,
	[JobStatus] [nvarchar](50) NULL,
	[JobDate] [date] NULL,
	[JobTime] [time](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[JobId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[MaskedSimplePatient]    Script Date: 4/21/2020 6:42:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MaskedSimplePatient](
	[Name] [nvarchar](10) NOT NULL,
	[Surname] [nvarchar](10) NOT NULL,
	[Phone] [nvarchar](50) NOT NULL,
	[Id] [int] NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[InsertDate] [date] NOT NULL,
 CONSTRAINT [PK_MaskedSimplePatient] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PATIENT]    Script Date: 4/21/2020 6:42:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PATIENT](
	[ADDRESS_LINE1] [char](30) NOT NULL,
	[ADDRESS_LINE2] [char](30) NOT NULL,
	[BIRTH_DATE] [datetime] NULL,
	[CITY] [char](25) NOT NULL,
	[OLD_DEPARTMENT] [char](2) NOT NULL,
	[ENTRY_DATE] [datetime] NULL,
	[FIRST_NAME] [char](25) NOT NULL,
	[HOME_PHONE] [char](10) NOT NULL,
	[COMMENT] [char](100) NULL,
	[HEIGHT_IN_INCHES] [smallint] NOT NULL,
	[WEIGHT_IN_POUNDS] [smallint] NOT NULL,
	[LAST_NAME] [char](25) NOT NULL,
	[PATIENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[PIN] [int] NULL,
	[RACE] [char](1) NOT NULL,
	[RELATIONSHIP_CODE] [char](1) NOT NULL,
	[SEX] [char](1) NOT NULL,
	[M_INITIAL] [char](1) NOT NULL,
	[SPONSOR_SSN] [char](9) NOT NULL,
	[STATE] [char](2) NOT NULL,
	[WORK_PHONE_EXT] [char](10) NOT NULL,
	[WORK_EXTENSION] [char](5) NOT NULL,
	[ZIP_CODE] [char](10) NOT NULL,
	[OPER_ID] [varchar](30) NULL,
	[UPDATE_TIMESTAMP] [datetime] NOT NULL,
	[QUALIFIED] [char](1) NULL,
	[DEPARTMENT] [varchar](128) NULL,
	[email_address] [char](60) NULL,
	[AUTH_ID] [int] NULL,
	[MEMBER_TYPE] [char](1) NULL,
	[FAMILY_CODE] [char](20) NULL,
	[FAMHIST] [char](1) NULL,
	[PERSHIST] [char](1) NULL,
	[SMOKING] [char](2) NULL,
	[EXERCISE] [varchar](2) NULL,
	[STRESS] [char](2) NULL,
	[ORGANDONOR] [char](1) NULL,
	[BPS] [int] NULL,
	[BPD] [int] NULL,
	[HISTORY_UPDATE_TIMESTAMP] [datetime] NULL,
	[SPONSOR] [int] NULL,
	[PERSONAL_UPDATE_TIMESTAMP] [datetime] NULL,
	[WEB_MEMBER_SINCE] [datetime] NULL,
	[ASKED_TO_LINK_RECORDS] [char](1) NOT NULL,
	[FAMHISTDIABETES] [char](1) NULL,
	[FAMHISTCANCER] [char](1) NULL,
	[PERSHISTDIABETES] [char](1) NULL,
	[PERSHISTBLOODPRESSURE] [char](1) NULL,
	[PERSHISTCANCER] [char](1) NULL,
	[PERSHISTCHOLESTEROL] [char](1) NULL,
	[DEPRESSION] [char](1) NULL,
	[ANXIETY] [char](1) NULL,
	[ALCOHOLCONSUMPTION] [char](1) NULL,
	[ALCOHOLCONSUMPTIONPROBLEM] [char](1) NULL,
	[VEHICLESAFETYALCOHOL] [char](1) NULL,
	[VEHICLESAFETYSPEEDING] [char](1) NULL,
	[VEHICLESAFETYSEATBELTS] [char](1) NULL,
	[EXAMPHYSICIAN] [char](1) NULL,
	[EXAMCOLORECTAL] [char](1) NULL,
	[EXAMPROCTOSCOPIC] [char](1) NULL,
	[EXAMPAPSMEAR] [char](1) NULL,
	[EXAMPELVIC] [char](1) NULL,
	[EXAMMAMMOGRAM] [char](1) NULL,
	[EXAMPSA] [char](1) NULL,
	[EXAMSKINCANCER] [char](1) NULL,
	[EXAMDENTAL] [char](1) NULL,
	[EXAMEYE] [char](1) NULL,
	[EXAMDIGITALRECTAL] [char](1) NULL,
	[OSTEOPOROSISTHIN] [char](1) NULL,
	[OSTEOPOROSISFAIRSKINNED] [char](1) NULL,
	[OSTEOPOROSISBROKENHIPWRIST] [char](1) NULL,
	[OSTEOPOROSISCORTICOSTEROIDS] [char](1) NULL,
	[OSTEOPOROSISAVOIDMINERALS] [char](1) NULL,
	[OSTEOPOROSISOVARIESREMOVED] [char](1) NULL,
	[EXAMPHYSICIAN_TIMESTAMP] [datetime] NULL,
	[EXAMCOLORECTAL_TIMESTAMP] [datetime] NULL,
	[EXAMPROCTOSCOPIC_TIMESTAMP] [datetime] NULL,
	[EXAMPAPSMEAR_TIMESTAMP] [datetime] NULL,
	[EXAMPELVIC_TIMESTAMP] [datetime] NULL,
	[EXAMMAMMOGRAM_TIMESTAMP] [datetime] NULL,
	[EXAMPSA_TIMESTAMP] [datetime] NULL,
	[EXAMSKINCANCER_TIMESTAMP] [datetime] NULL,
	[EXAMDENTAL_TIMESTAMP] [datetime] NULL,
	[EXAMEYE_TIMESTAMP] [datetime] NULL,
	[EXAMDIGITALRECTAL_TIMESTAMP] [datetime] NULL,
	[TSCORE] [decimal](4, 1) NULL,
	[GALEL] [decimal](4, 3) NULL,
	[GALE5] [decimal](4, 3) NULL,
	[NUMBER_OF_CHILD] [char](10) NULL,
	[AGE_1_3] [char](10) NULL,
	[AGE_4_7] [char](10) NULL,
	[AGE_8_12] [char](10) NULL,
	[AGE_13_18] [char](10) NULL,
	[AGE_19_35] [char](10) NULL,
	[AGE_36_55] [char](10) NULL,
	[AGE_56_70] [char](10) NULL,
	[AGE_OVER70] [char](10) NULL,
	[FASTED_BEFORE_EXAM] [int] NULL,
	[TEAM] [int] NULL,
	[LAB] [int] NULL,
	[HMO] [char](10) NULL,
	[PPO] [char](10) NULL,
	[MEDICARE] [char](10) NULL,
	[OTHER] [char](10) NULL,
	[NONE] [char](10) NULL,
	[PCX_SIGNATURE] [varchar](50) NULL,
	[SUBSCRIPTION] [char](10) NULL,
	[MEDHIST_SCAN_TIMESTAMP] [datetime] NULL,
	[SSN] [varchar](9) NULL,
	[LAST_FORM_TYPE_IMPORTED] [varchar](10) NULL,
	[EMAIL_EXCLUDED] [char](1) NULL,
	[DISABLE_WEB_ACCESS] [char](1) NULL,
	[DISABLE_LINKING] [char](1) NULL,
	[LAST_QUALIFIER_RUN_START] [datetime] NULL,
	[LAST_QUALIFIER_RUN_END] [datetime] NULL,
	[BP_UPDATE_TIMESTAMP] [datetime] NULL,
	[DENY_ACCESS_BY_AFFILIATES] [char](1) NULL,
	[PREFERRED_TIME_TO_CONTACT_OLD] [int] NULL,
	[PREFERRED_TIME_TO_CONTACT_TIMESTAMP] [datetime] NULL,
	[PERMISSION_TO_CALL_OLD] [char](1) NULL,
	[ASPIRIN_THERAPY] [tinyint] NULL,
	[CELL_PHONE] [char](10) NULL,
	[CONTACT_PHONE] [char](10) NULL,
	[PREFERRED_TIME_TO_CONTACT] [varchar](10) NULL,
	[VIP_STATUS] [bit] NULL,
	[PERMISSION_TO_CALL] [bit] NULL,
	[SPEAK_ONLY_SPANISH] [char](1) NULL,
	[SPOUSE_NAME] [varchar](50) NULL,
	[BODY_FAT] [float] NULL,
	[LAST_4_DIGIT_OF_SSN] [char](4) NULL,
	[COTININE_OLD] [char](8) NULL,
	[BRANDED_SITE_REDIRECT2] [char](1) NULL,
	[BRANDED_SITE_REDIRECT] [char](1) NOT NULL,
	[EKG_BY] [smallint] NULL,
	[UNIQUE_ID] [varchar](50) NULL,
	[UNIQUE_ID_AFFILIATE_ID] [int] NULL,
	[LONGITUDE] [float] NULL,
	[LATITUDE] [float] NULL,
	[BAD_ADDRESS] [char](1) NULL,
	[ADDRESS_GEOCODING_PROCESS_ID] [varchar](50) NULL,
	[LATEST_LR_UID] [int] NULL,
	[LATEST_CHEMCBC_LR_UID] [int] NULL,
	[JOB_ORDER_CLIENT_ID] [int] NULL,
	[SPONSOR_UNIQUE_ID] [varchar](50) NULL,
	[EVALUATION_LOCATION] [varchar](50) NULL,
	[BMI] [float] NULL,
	[INSURANCE_TYPE] [tinyint] NULL,
	[INSURANCE_GROUP_ID] [varchar](50) NULL,
	[CUSTOM_FIELD_1] [varchar](50) NULL,
	[CUSTOM_FIELD_2] [varchar](50) NULL,
	[CUSTOM_FIELD_3] [varchar](50) NULL,
	[HAS_HSA_ACCOUNT] [tinyint] NULL,
	[HAS_FSA_ACCOUNT] [tinyint] NULL,
	[FAMHISTBREASTCANCER] [char](1) NULL,
	[FAMHISTCOLONCANCER] [char](1) NULL,
	[FAMHISTPROSTATECANCER] [char](1) NULL,
	[FAMHISTOVARIANCANCER] [char](1) NULL,
	[PERSHISTBREASTCANCER] [char](1) NULL,
	[PERSHISTCOLONCANCER] [char](1) NULL,
	[PERSHISTPROSTATECANCER] [char](1) NULL,
	[PERSHISTOVARIANCANCER] [char](1) NULL,
	[SPANISH_SPEAKING] [tinyint] NULL,
	[LAST_CLIENT_LOCATION_ID] [int] NULL,
	[LAST_JOB_ID] [int] NULL,
	[LAST_JOB_APPOINTMENT_ID] [int] NULL,
	[LAST_CLIENT_ID] [int] NULL,
	[LAST_AFFILIATE_ID] [int] NULL,
	[LAST_JOB_APPOINTMENT_DATE_TIME] [datetime] NULL,
	[LAST_LAB_REPORT_ID] [int] NULL,
	[LAST_LAB_REPORT_DRAWN_DATE] [datetime] NULL,
	[LAST_MEDICAL_HISTORY_ID] [int] NULL,
	[LAST_PATIENT_CODE_ID] [int] NULL,
	[LAST_MEDICAL_HISTORY_IMPORT_DATE_TIME] [datetime] NULL,
	[LAST_TRIGGER_UPDATE_TIMESTAMP] [datetime] NULL,
	[SPEC_COND] [tinyint] NULL,
	[HEALTH_STATUS] [tinyint] NULL,
	[READINESS_TO_IMPROVE] [tinyint] NULL,
	[FLU_SHOT] [tinyint] NULL,
	[FLU_SHOT_TIMESTAMP] [datetime] NULL,
	[VISION_IMPAIRED] [tinyint] NULL,
	[HEARING_IMPAIRED] [tinyint] NULL,
	[NON_ENGLISH_SPEAKER] [tinyint] NULL,
	[DOCTOR_NAME] [varchar](50) NULL,
	[DOCTOR_FAX] [varchar](10) NULL,
	[DOCTOR_PHONE] [varchar](10) NULL,
	[DOCTOR_EMAIL] [varchar](60) NULL,
	[OPT_OUT_TEXT_MSG] [bit] NULL,
	[OPT_OUT_DOC_INFO] [bit] NULL,
	[PERSHISTOTHERCANCER] [char](1) NULL,
	[TOBACCO_QUIT] [char](1) NULL,
	[TOBACCO_FREQ] [char](1) NULL,
	[TOBACCO_TYPE] [char](1) NULL,
	[EXERCISEMOD] [char](1) NULL,
	[EXERCISEACT] [char](1) NULL,
	[DASS_DEPRESSION_RATING] [int] NULL,
	[DASS_ANXIETY_RATING] [int] NULL,
	[DASS_STRESS_RATING] [int] NULL,
	[AGE_1_6_M] [bit] NULL,
	[AGE_1_6_F] [bit] NULL,
	[AGE_7_12_M] [bit] NULL,
	[AGE_7_12_F] [bit] NULL,
	[AGE_13_17_M] [bit] NULL,
	[AGE_13_17_F] [bit] NULL,
	[SMOKING_UPDATE_TIMESTAMP] [datetime] NULL,
	[EXERCISE_UPDATE_TIMESTAMP] [datetime] NULL,
	[HEIGHT_UPDATE_TIMESTAMP] [datetime] NULL,
	[WEIGHT_UPDATE_TIMESTAMP] [datetime] NULL,
	[EMPLOYMENT_STATUS_ACTIVE] [bit] NULL,
 CONSTRAINT [PK__PATIENT__0CDAE408] PRIMARY KEY CLUSTERED 
(
	[PATIENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SimplePatient]    Script Date: 4/21/2020 6:42:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SimplePatient](
	[Name] [nvarchar](10) NOT NULL,
	[Surname] [nvarchar](10) NOT NULL,
	[Phone] [nvarchar](50) NOT NULL,
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[InsertDate] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[StoreChecksumSimplePatient]    Script Date: 4/21/2020 6:42:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[StoreChecksumSimplePatient](
	[Name] [nvarchar](10) NOT NULL,
	[Surname] [nvarchar](10) NOT NULL,
	[Phone] [nvarchar](50) NOT NULL,
	[Id] [int] NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[InsertDate] [date] NOT NULL,
	[Checksum] [int] NOT NULL,
	[Status] [varchar](1) NOT NULL,
	[JobId] [int] NULL,
	[LogId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[UpdatedRowSet]    Script Date: 4/21/2020 6:42:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[UpdatedRowSet](
	[Name] [nvarchar](10) NOT NULL,
	[Surname] [nvarchar](10) NOT NULL,
	[Phone] [nvarchar](50) NOT NULL,
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[InsertDate] [date] NOT NULL,
	[Checksum] [int] NOT NULL,
	[Status] [varchar](1) NOT NULL,
	[JobId] [int] NULL,
	[LogId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__ADDRESS__21EB0F87]  DEFAULT (' ') FOR [ADDRESS_LINE1]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__ADDRESS__22DF33C0]  DEFAULT (' ') FOR [ADDRESS_LINE2]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__CITY__23D357F9]  DEFAULT (' ') FOR [CITY]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__DEPARTM__24C77C32]  DEFAULT (' ') FOR [OLD_DEPARTMENT]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF_PATIENT_ENTRY_DATE]  DEFAULT (getdate()) FOR [ENTRY_DATE]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__FIRST_N__26AFC4A4]  DEFAULT (' ') FOR [FIRST_NAME]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__HOME_PH__27A3E8DD]  DEFAULT ('0000000000') FOR [HOME_PHONE]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__HEIGHT___28980D16]  DEFAULT ((0)) FOR [HEIGHT_IN_INCHES]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__WEIGHT___298C314F]  DEFAULT ((0)) FOR [WEIGHT_IN_POUNDS]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__LAST_NA__2A805588]  DEFAULT (' ') FOR [LAST_NAME]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__RACE__2C689DFA]  DEFAULT (' ') FOR [RACE]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__RELATIO__2D5CC233]  DEFAULT (' ') FOR [RELATIONSHIP_CODE]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__SEX__2E50E66C]  DEFAULT (' ') FOR [SEX]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__M_INITI__2F450AA5]  DEFAULT (' ') FOR [M_INITIAL]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__SPONSOR__30392EDE]  DEFAULT ((0)) FOR [SPONSOR_SSN]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__STATE__32217750]  DEFAULT (' ') FOR [STATE]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__WORK_PH__33159B89]  DEFAULT ('0000000000') FOR [WORK_PHONE_EXT]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__WORK_EX__3409BFC2]  DEFAULT ('  ') FOR [WORK_EXTENSION]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__ZIP_COD__34FDE3FB]  DEFAULT (' ') FOR [ZIP_CODE]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__OPER_ID__35F20834]  DEFAULT (user_name()) FOR [OPER_ID]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF__PATIENT__UPDATE___36E62C6D]  DEFAULT (getdate()) FOR [UPDATE_TIMESTAMP]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF_PATIENT_QUALIFIED_1__54]  DEFAULT ('Y') FOR [QUALIFIED]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF_PATIENT_ASKED_TO_LINK_RECORDS]  DEFAULT ('N') FOR [ASKED_TO_LINK_RECORDS]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF_PATIENT_FASTED_BEFORE_EXAM]  DEFAULT ((2)) FOR [FASTED_BEFORE_EXAM]
GO
ALTER TABLE [dbo].[PATIENT] ADD  CONSTRAINT [DF_PATIENT_BRANDED_SITE_REDIRECT]  DEFAULT ('Y') FOR [BRANDED_SITE_REDIRECT]
GO
